### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by koachcode** [joskalenda/to-do-list#8]
#  Review on UI/UX
1. All items in the list should not have the editable functionality by default so that the user won't edit a task unknowingly 
2. When editing an item in the list, they should be an event to exist the editing functionality performed
3. The footer should not be fixed, as it hides the button of  " clear completed" when more content is added to the list
4. The rotate icon on the top right corner of the UI, should be more descriptive on what it performs.

# Review on Code
1. Try adding some comments to areas where it is necessary for your code.
2.  Well organized Code, using the module

## You have done a good job so far, keep it up 👍

**Comment by joskalenda** [comment]
Thanks, I will take all of these into consideration
